### ISSUE TITLE
dc-monitor of syncs with qp

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#138]
make the dc-monitor be qp-aware.
1.  read the qp from the sync infotons
1. create new dc virtual infotons that accept qp
1. make sure that the monitor won't mix two different qps from the same dc-id
1. stucks
   1. on is stuck and one is working - kill the jvm
   1. one is on horizon and there are more infotons on the source that should be synced - don't kill the jvm

**Comment by AnnaGrebnev** [comment]
@yanpom to test
