### ISSUE TITLE
upgrade cassandra to latest patch version (2.1.18)

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#149]
upgrade to latest patch version (currently 2.1.18)

**Comment by YoniMataraso** [comment]
Hi @hochgi,
Can you please split into two stories one for the patch version and the second to the latest 3.x version

**Comment by AnnaGrebnev** [comment]
@Ivan-Shestakov to test

**Comment by yanpom** [comment]
Tested
