### ISSUE TITLE
play 2.6 upgrade

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#167]
We should try to upgrade + benchmark to see no perf regression since default backend is akka-http instead of netty.
This will most likely to affect all stream APIs (hoping for perf improvements)

**Comment by AnnaGrebnev** [comment]
@Ivan-Shestakov please install current and check sstream + sanity

**Comment by Ivan-Shestakov** [comment]
Verified that after this change there was not performance degradation (K->L).
Analyzed gatling reports for stream tests from versions K,L,N,O.
Partial table to demonstrate (more values in actual reports):  

| Version | sstream | sstream-with-data | mstream | mstream-with-data |
| ---- | ---- | ---- | ---- | ---- | 
| K | 3.8 | 23.8 | 7.1 | 23.9 |
| L | 2.9 | 23.7 | 4.4 | 23.6 |
| N | 7.8 | 47 | 13.76 | 25 |
| O | 5 | 30 | 9.6 | 20.8 |
