### ISSUE TITLE
Problem with Web UI classpath?

### ISSUE THREAD

**Issue by ajs6f** [thomsonreuters/CM-Well#189]
Hello, I am very much a Scala newbie, so I apologize if this is an inappropriate question for this tracker. I was able to build CM-Well and mostly (g) to start it up. But after building up most of its components after a `pe install` I ran into a missing method:

```
Info:     Web Service boot in progress ()
Info:   waiting for ws...
java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
  at akka.stream.StreamSubscriptionTimeoutSettings$.apply(ActorMaterializer.scala:518)
 ```
and instead of getting the Web UI at `localhost:9000` I got the message `Infoton not found`. 

I would appreciate any advice on where to start debugging this-- I can find a number of `akka-actor` JARs in the project after building, and I believe that `akka-actor` is the library in question, but I'm not quite sure which ones are in use or how that is determined.

**Comment by hochgi** [comment]
This is a known & annoying issue. The install process levreges the scala REPL, which loads on the classpath the jars on your local scala installation lib dir. One of this jars is akka-actor, and this results in the issue you describe. A quick workaround is to simply delete the jar from the scala installation dir.

Maybe we should consider using another REPL library (ammonite?).

**Comment by TRnonodename** [comment]
@ajs6f if you haven't seen it before, check out the [building tutorial ](https://github.com/thomsonreuters/CM-Well/blob/master/docs/Tutorial.Building.md)which touches on the Akka conflict.

**Comment by ajs6f** [comment]
That did it, guys, thanks very much!
