### ISSUE TITLE
Ingest of unsufficient data should return proper error code and not 200 Success

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#199]
ingest with path only (or parent or uuid) doesnt acceptable by CMWELL but the return code is 200
Proper error message should return

**Comment by hochgi** [comment]
most appropriate code seems like 422:
> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions.
> ### Wikipedia
>
> The request was well-formed but was unable to be followed due to semantic errors.

**Comment by yanpom** [comment]
Following returns with error code 422:
ingested data was well formed, but is meaningless and has no affect. error logged with id [01S]
Following in ws log:
2017-10-24 13:03:58,159 [ForkJoinPool-1-worker-35]                   WARN  controllers.InputHandler             - [01S] bad user ingest resulted in parsed response: ParsingResponse(Map(),Map(),Set(cm-well-uk-
lab.int.thomsonreuters.com),Map(),Map(),List(),Map())
