### ISSUE TITLE
Properly use the config on akka connection pools

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#205]
This is the same issue as #195.
Sparql Triggered processor uses connection pool that overrides the config. make sure it's done right.

- [x] fix the tsv get connection pool in sparql triggered processor
- [x] check newHostConnetionPool, newCachedConnetionPool etc. for config overrides generally on whole cm-well
- [x] currently it shouldn't work. Why there isn't any error printed in the logs??? (the size issue is fixed in code by withoutSizeLimit)

**Comment by e-orz** [comment]
Fixed by PR #242

**Comment by AnnaGrebnev** [comment]
@Ivan-Shestakov - please test it
