### ISSUE TITLE
New APIs for debuging & easier investigation 

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#210]
e.g. `_es/UUID`, `_path/some/path?limit&reactive&...`
To retrieve ES sources, cas path rows, etc'...
(`_kafka/OFFSET`???)

**Comment by AnnaGrebnev** [comment]
@hochgi can you please provide more examples?

**Comment by AnnaGrebnev** [comment]
@Ivan-Shestakov please check capabilities of this new Debug API's and let @yanpom and me know if it can be used for the backend tests.
