### ISSUE TITLE
typesCache deadlocks

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#260]
@e-orz added the following commit:
https://github.com/thomsonreuters/CM-Well/pull/258/commits/5df365c002753bab6d0135e8b591b3c1fa279cb6
to help understand the sporadic failures of sorted search test.
It appears we get into some deadlock...
here's what's the test output is for that commit.
```
[info] - get sorted by latitude (all share property) *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at cmwell.it.SearchTests$$anonfun$1$$anonfun$14$$anonfun$apply$17.apply(SearchTests.scala:142)
[info]   at cmwell.it.SearchTests$$anonfun$1$$anonfun$14$$anonfun$apply$17.apply(SearchTests.scala:141)
[info]   at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at scala.util.Success.map(Try.scala:237)
```

**Comment by e-orz** [comment]
Are you sure it's a dealock in a code and not in tests? Runnng
https://github.com/thomsonreuters/CM-Well/blob/5df365c002753bab6d0135e8b591b3c1fa279cb6/server/cmwell-it/src/it/scala/cmwell/it/SearchTests.scala#L142
inside a test might never happen because the execution context only allows one thread.

**Comment by hochgi** [comment]
It might be. Easy enough to test. Lets just use `scala.concurrent.ExecutionContext.global` directly (and explicitly) in the test.
