### ISSUE TITLE
Allow both 2017 and 2018 private keys

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#299]
`play.crypto.secret` should be changed. During the period of granting new Tokens for existing users, both new and old configured values should be supported.

**Comment by hochgi** [comment]
Related ref: #237

**Comment by Ivan-Shestakov** [comment]
Tested on Octopus build with git commit hash 6262881aa38ce6db59d4d5f19db4e1a0ca880461

On 2 environments (New and Old) created 2 users. 
1 permitted and 1 forbidden to write to specific folder `/A`
Attempt to write to this folder using tokens got after login (environment on which login done marked with @ sign)
Expected result: user with token from old environment can still use it on new for backward compatibility. 

Env\User | user1@Old | user1@New | user2@Old | user2@New
------------ | ------------- | ------------- | -------------- | ---------------- |
New | :white_check_mark: | :white_check_mark:  |  :x:  |  :x:   
Old | :white_check_mark: |  :x:  | :x:  |  :x:  

Results are as expected.
