### ISSUE TITLE
/proc/dc/someId doesn't look in the history

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#318]
DISCUSSION: Is it really a bug?
Known components that use this mechanism:
1. DcMonitor - to check if the sync is running or stuck
1. DataCenterSyncManager - During sync initialization it checks what is the last index time already synced on the target environment
1. UI - The user can check the last index time synced

This bug was found during adding the current only sync to the sync system. It seems that it checked only current even though the sync took also history. It never affected anybody.
Current is always synced and the last index time will be correct when all the data is there. The issue could be with a big chunk of history and the monitor will "think" that the sync is stuck.

What do you think?

**Comment by hochgi** [comment]
Old data path (old FTS), is hard coded to search against current and history indices AFAIK.
In new data path, it seems like a bug due to careless C&P.

**Comment by e-orz** [comment]
Fixed in PR #323

**Comment by Ivan-Shestakov** [comment]
After discussion with @e-orz  - reconstructing data to reproduce this issue is time and resource intensive.
