### ISSUE TITLE
Remove large amount of spurious log messages from Cassandra

### ISSUE THREAD

**Issue by Andy-42** [thomsonreuters/CM-Well#348]
There are large numbers of log messages generated by Cassandra such as the following:

> WARN  13:51:50 Batch of prepared statements for [data2.infoton] is of size 19957, exceeding specified threshold of 5120 by 14837.
> WARN  13:51:52 Batch of prepared statements for [data2.infoton] is of size 12703, exceeding specified threshold of 5120 by 7583.
> WARN  13:51:52 Batch of prepared statements for [data2.infoton] is of size 15987, exceeding specified threshold of 5120 by 10867.

These messages (251 of them) were generated simply by starting pe in a clean cm-well-data directory. Some of the infotons that are uploaded during initialization cause this to happen.

These appear in cas/stdout.log. There is only one place where this log message could be generated: IRWServiceNativeImpl.writeAsyncDataOnly, where it uses an unlogged batch to write all the fields of an infoton atomically.

The logging done by C* is erroneous since it it warning about allocating the buffers that would be needed for a multi-partition unlogged batch. In this case, the unlogged batch is will always be for a single-partition, so C* is logging this message unnecessarily. This issue is fixed in Cassandra 3.6  [CASSANDRA-10872](https://issues.apache.org/jira/browse/CASSANDRA-10876).

The fix is to modify the C* configuration so that the buffer configuration is large enough that C* no longer logs the messages. This will just change logging, and doesn't alter how C* processes these batched statements in any way.

**Comment by Andy-42** [comment]
This turns out to be a simple change. I had some issues trying to verify the fix, but that had to do with some confusion around my configuration, and not with the fix at all. You can see these log messages the first time that you start up in a clean environment. The data that is loaded into the system initially includes some infotons that are large enough to cause these messages to occur. Applying the change to the configuration makes them go away.

**Comment by Andy-42** [comment]
This was change was merged in 0b6b44f.

Looking to see if there are other high-volume messages that need to be turned down.

**Comment by Ivan-Shestakov** [comment]
Validate on git commit version 8e2043f2784f3bfda6434b4763d498fb9b0ad442 when starting up clean environment, the only warnings are about:
 * OpenJDK is not recommended. Please upgrade to the newest Oracle Java release
* Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enab┤
led. Increase RLIMIT_MEMLOCK or run Cassandra as root.

Moving to Closed in dashboard.
