### ISSUE TITLE
DCSync - print Info log on TSV retrieve start

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#382]
Each process should have start line in logs in INFO state:
bulk-consume
slow-bulk
consume

**Comment by GuyGuterman** [comment]
NOTE; remove the slow bulk state from the dcSync agent [#435](https://github.com/thomsonreuters/CM-Well/pull/435)

Search over application.log and gz since yesterday (new V) and found messages as expected. 

Moving to Done in the dashboard.
