### ISSUE TITLE
DCSync - Add retry to bulk-consume

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#384]
Add another retry to bulk-consume before reducing to slow-bulk

**Comment by GuyGuterman** [comment]
NOTE; remove the slow bulk state from the dcSync agent #435 

Validated by searched over bc/application.log and find a case that validates the infected scenario.
The system operated as required in the case of TSV's **FAILED** and make an attempt once again respectively as required.
Date: ```8.02.18``` P:```1S5I9CH28IN6dy1xmcMQJhgkAvgP20rUj3PTlY6e51PgjlcMfbWUXJeVyzqmKUwqvWW5sKTxV5jkzhuV1IqfopVVrh8rfRS1yq-t6AWWjQJg```

> The result: Works as expected

Moving to Done in the dashboard.
