### ISSUE TITLE
Build for cmwell-data-tools and cmwell-data-tools-app doesn't work as documented

### ISSUE THREAD

**Issue by Andy-42** [thomsonreuters/CM-Well#390]
The build for the cmwell-data-tools and cmwell-data-tools-app projects don't work as described in the documentation. They will build as part of the CM-Well project, but building these projects on their own (as described in the documentation) doesn't work because of missing sbt functionality that is defined in the root CM-Well project.

This issue is to ensure that these projects can be built separately from the CM-Well project (as described in the documentation), and to verify that the documentation for building and running these projects is correct.

**Comment by Andy-42** [comment]
It would be simpler to just build the entire CM-Well project since this will include the build for data tools as well.

The description of how the tools are packaged and run is out of date, so this issue could be resolved by updating documentation.

**Comment by Andy-42** [comment]
Should be:

1. Navigate to the CM-Well/server directory.
2. Run the following command: sbt pack

The name of the jar files created is different now.

**Comment by YoniMataraso** [comment]
They are trying to build data tools,
Yoni

**Comment by Andy-42** [comment]
The sbt projects for cmwell-data-tools and cmwell-data-tools-app use sbt infrastructure from the top-level project, so the simple solution is just to build the top-level server project. They could be modified to build separately - is it worth doing?

**Comment by e-orz** [comment]
@Andy-42 and @YoniMataraso The correct "syntax" is:
`sbt dataToolsApp/pack` or `sbt dataToolsApp/packArchive` to pack it to an archive.
The results are in `cmwell-data-tools-app/target/pack` for the extracted version and `cmwell-data-tools-app/target/cmwell-data-tools-app-1.5.x-SNAPSHOT.{zip, tar.gz}` for the archive one.

which works (just tested).

**Comment by Ivan-Shestakov** [comment]
I believe the correct way to handle this is to update documentation to reflect what @e-orz have written above (as Andy have suggested in first comment).

**Comment by e-orz** [comment]
The Hub is TR internal site. We must have the official docs right (I think they are) and link from the hub to them. No need to update in both places.

**Comment by Andy-42** [comment]
This is an old issue, and we aren't going to take any more steps, so closing.
