### ISSUE TITLE
STP Dashboard Enhancements

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#392]
After a discussion with @AnnaGrebnev , @yanpom , @e-orz a list of initial enhancements for the STP dashboard has been determined:

* Each job has several statuses. The dashboard should show the status of each job
* Each job also has several sensors. The dashboard should show the status of each sensor
* Failure reason / exceptions should be displayed by the sensor to save the end user from having to navigate to the logs
* We should show last index time for each sensor
* Show number of processed / updated infotons
* Show current position of STP

**Comment by e-orz** [comment]
my additions:
* Show number of processed / updated infotons - for each job separately (each job should unite all the sensor so it cannot be done for each sensor)
* Show current position of STP - has no meaning (I think) the position should be for each sensor

**Comment by e-orz** [comment]
my additions:
* Show number of processed / updated infotons - for each job separately (each job should unite all the sensor so it cannot be done for each sensor)
* Show current position of STP - has no meaning (I think) the position should be for each sensor

**Comment by nicklester** [comment]
Also add the infoton moving average rate removed as part of #450

**Comment by nicklester** [comment]
- [ ] All Job Statuses reflected on the dashboard
- [ ] Show status of each sensor
- [ ] Exception text string now displays for a failed job
- [ ] Last index time shows for each sensor
- [ ] Infotons received show per agent
- [ ] Infotons ingested and failed (processed) show in dashboard
- [ ] Re-add the infoton moving average rate for infotons received

**Comment by nicklester** [comment]
@AnnaGrebnev , @yanpom - I believe that a lot of the requirements for this ticket are now implemented. I created a checklist to track. Can you check?
