### ISSUE TITLE
searching by content.* or link.* fails because it is not treated as system field

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#398]
e.g. `qp=content.data:...` or `qp=content.mimeType:...` fails because CM-Well tries to resolve ns prefix `data` or `mimeType`...

**Comment by AnnaGrebnev** [comment]
@hochgi can you please elaborate more about link.* evaluation* + adding InputStrream - what does it exactly do (example) and if you need us to do specific cases please add What to test part as well.

**Comment by hochgi** [comment]
@AnnaGrebnev I fixed the field evaluation to treat special properties properly.
system is not the only special namespace. link & content should get same treatment.
other changes are internal... nothing to test.

**Comment by GuyGuterman** [comment]
Tested again as it was in pull request [#399](https://github.com/thomsonreuters/CM-Well/pull/399).
Test passed, moving to Closed in the dashboard.
