### ISSUE TITLE
optimize consume to return bigger nulks on default when feasable

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#400]
indirectly related to #238
if neither gqp nor xg/yg was supplied, we can handle a much larger chunk (a reasonable size can be 3K instead of 100).
in case we also need to supply data, we can do it "reactively" without postponing reponse, using a chunked response.
if gqp/xg/yg were supplied, we should stick to a smaller chunk size to not over burden the system.

This translate directly to better performance of regular consumes → dc sync should benefit a lot from this.

**Comment by Ivan-Shestakov** [comment]
@nruppin @YoniMataraso 
This change should be reflected in documentation - 
https://github.com/thomsonreuters/CM-Well/blob/master/docs/API.Stream.ConsumeNextChunk.md

**Comment by YoniMataraso** [comment]
I agree @Ivan-Shestakov - we will update the documentation.

**Comment by nruppin** [comment]
Gilad, please specify exactly what to add to documentation and where.
What does "we should stick to a smaller chunk size" mean? CM-Well determines the chunk size and not the user, correct? Are you saying that if xg/yg/gqp is used, CMW returns a chunk size of about 100 (and with no traversal, 3000)? Is this relevant to both consume and bulk-consume?

**Comment by hochgi** [comment]
@nruppin bulk-consume cannot be "expanded" at all. xg/yg/gqp will be ignored.
this only relevant to regular consume.
Up until now, consume started by performing a sorted search with a length of 100.
Now, the default is 3000, unless xg/yg/gqp is also supplied, which in this case it is still 100.
