### ISSUE TITLE
Following error message should be more descriptive

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#412]
Following error message when trying to _ow deleted infoton should be more descriptive:
{"success":false,"error":"requirement failed: in overwrites API all meta data must be present! no implicit inference is allowed. (every infoton must have all relevant system fields added)"}

**Comment by hochgi** [comment]
to add some context:
you also get this message when you attempt to ingest infoton with dataCenter id matching the cluster you ingest to.

**Comment by Ivan-Shestakov** [comment]
Verified - see results in comments of https://github.com/thomsonreuters/CM-Well/pull/416
