### ISSUE TITLE
STP - Sparql "bad data" logs should be written to different log

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#434]
Lot of following logs written to dc application.log
2018-01-25 02:14:58,544 -well-egl1-akka.actor.default-dispatcher-79] INFO  bad-data                             - [ingester-symric] data: Busy, try again later

Those "bad data" items should be written to tools-red.log or some other defined log for sparql failures

**Comment by bryaakov** [comment]
See issue #503

**Comment by nicklester** [comment]
Bad data logging is not defined for the STP agent (only for data tools app). Need to add support in dc logback.xml for bad data logs.

**Comment by nicklester** [comment]
PR #613 enables the bad data log in line with what is currently logged to bad data in the data tools app

**Comment by yanpom** [comment]
Verified and Closed
