### ISSUE TITLE
STP Engine - Source configuration change requires a restart/upgrade

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#442]
In order to change physical view source name from local to prod or vice versa, there is a need to manually change reference.conf file which is located in cmwell-sparql-triggered-processor-agent_2.12-1.5.93.jar
Than in order to those changes apply, there is a need in upgrade of the system
This configuration should be less complicated and be a part of agent creation (maybe its should be one of the agent parameters)

**Comment by nicklester** [comment]
Added a new configuration option in the yml:

hostUpdatesSource: <http url of source cmwell>

If this is set it will override the value set in reference.conf, otherwise it will use the value set in reference.conf

**Comment by nicklester** [comment]
P.S - for changes to take effect you need to re-upload the yml and pause and un-pause the job. This will cause the config to be reloaded.

**Comment by e-orz** [comment]
@nicklester Are you sure pause-resume will be enough? As far as I remember full removal of the STP yaml infoton and re-ingest of it is needed.

Anyway, Naomi should document it cc @nruppin
