### ISSUE TITLE
STP Agent - Physical view source machine name should be written in logs/dashboard

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#443]
Following is written in agents.log on agent start:
018-01-28 14:34:35,533 -well-egl1-akka.actor.default-dispatcher-20] INFO  c.t.d.sparql.SparqlProcessorManager  - Got start request for job [job: industry, config name:None, sensors: industryindustry] from the user
2018-01-28 14:34:37,206 -well-egl1-akka.actor.default-dispatcher-20] INFO  c.t.d.sparql.SparqlProcessorManager  - starting job [job: industry, config name:None, sensors: industryindustry]
2018-01-28 14:34:37,228 -well-egl1-akka.actor.default-dispatcher-20] INFO  BufferFillerActor [industryindustry] - starting BufferFillerActor

There should be a physical view source machine name mentioned in the logs and also in dashboard. User should suppose to know from what environment data is pulled

**Comment by nicklester** [comment]
Added source machine for STP to dashboard and to relevant STP logs. See screenshots

**Comment by nicklester** [comment]
![screen shot 2018-02-14 at 20 05 51](https://user-images.githubusercontent.com/1490089/36225417-82fe2154-11c2-11e8-92d1-362b1e8dad12.png)
![screen shot 2018-02-14 at 20 05 26](https://user-images.githubusercontent.com/1490089/36225418-8320209c-11c2-11e8-8638-d44f894008aa.png)
