### ISSUE TITLE
STP Dashboard - Incorrect calculation of infoton-rate

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#450]
Infoton rate doesn't calculated from the agent start, but it seems that it calculated per small amount of time - the jumps between 30inf/sec to 15/sec to 0/sec are very high
The calculation should be => the number of infotons divide (current time minus time of agent start)

**Comment by nicklester** [comment]
@e-orz before I send a pull request, I'd like your opinion on this change if you have a min..

**Comment by yanpom** [comment]
Verified and closed
