### ISSUE TITLE
STP Dashboard - Point in time stays 1970-01-01T00:00	

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#451]
Sensor is working,pulling and materilizing infotons but its point in time remains 
1970-01-01T00:00

Also, its not quit understood what point of time is  - we should propably to rename it to remote index time (as in dcsync) or some more propriate name

**Comment by yanpom** [comment]
Please see attached print screen

**Comment by nicklester** [comment]
Token is saved after reading so many paths, or up until a certain time window has elapsed. So until  a token has been saved I think the token will be read as 0, which interprets to 1970-01-01T00:00 when converted to a date. 

What should we do in this circumstance? Show empty field? Or some text? @yanpom  / @YoniMataraso

**Comment by e-orz** [comment]
The token is actually the last persisted time (the time STP will start the sensor from). A time of 0 is actually saying it will start from the beginning which is the truth...

**Comment by nicklester** [comment]
Correct. Just wondering if we should show an empty field rather than 1970.... I will change this and submit PR - and we can change logic if need be :)
