### ISSUE TITLE
STP agent - Token per sensor creation each X minute, overloads infotons history

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#457]
For each sensor, there is token infoton which created each X minutes. This is overloading the infoton and makes it very heavy . For each sensor, after a month of running we can have hundreds of versions in history multiple number of sensors in system, We need to find some better solution:
1. Remove old infotons from history 
2. Use zookeeper for tokens storage

**Comment by YoniMataraso** [comment]
This is current behavior of CM-Well, Nothing to do with STP  for that matter.
Closing the issue as this will be addressed by a more generic solution for infotons versions.
