### ISSUE TITLE
STP Dashboard - There is a need in another state of agent execution

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#458]
Apart from Active and Non-Active, there is a need for another state in stp dashboard per agent/sensor
Incremental Updates/Horizon state is needed to show the user that agent finished its normal work and now is in waiting/per demand condition. In this case the infoton rate is not needed also (or we can use this field for incremental/waiting status.

**Comment by nicklester** [comment]
We should add a new column to the agent table to show whether we are in Horizon

**Comment by nicklester** [comment]
![screen shot 2018-02-20 at 13 57 31](https://user-images.githubusercontent.com/1490089/36427819-16c91222-1646-11e8-9281-1926f12cd927.png)
