### ISSUE TITLE
STP Dashboard - Materialized and received infotons incorrect statistics

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#459]
In STP dashboard, there is a high gap between materilized and received number of infotons 
For example, for person agent after almost 2 days of running there are 
Materilized: 1,751,822 infotons
Received (pulled) : When summarizing all sensors: 1,916,878 infotons
and when searching in CMwell, how much infotons there are I get also different number: 1,725,211 infotons

So, there are two issues:
1. there is 26,600 infotons gap between materialized view statistics and how many infotons there are actually exist in CMWELL (are we counting also the failed ones?)
2. There us a huge gap between pulling and ingesting data - 165,000 infotons - the bg queue is empty - there should not be such gap in statisitcs

**Comment by nicklester** [comment]
I don't think Materialized infotons in the dashboard shows successfully ingested infotons. These stats derive from the Downloader - i.e. infotons retrieved from the source host

**Comment by nicklester** [comment]
Ok - the way I think this works is:

Received infotons: STP either queries and obtains 10000 paths, or as many as the stream can achieve in a specified time window.

Materialized infotons: Sparql queries run to produce the materialized infotons. This is more time consuming as there is an API request for each queried path. This doesn't relate to actually ingested infotons as they could fail...

New dashboard enhancement in #467 #488 shows the number of infotons per agent successfully ingested and the number failed. I found that with a correctly configured environment the success figures for ingest lagged materialized by a few infotons as the ingest progressed. I think this is to be expected.

Please can you retest once PR #488 is merged, bearing this in mind, as I do think it is working as it should.
