### ISSUE TITLE
STP Dashboard - Add failed ingested infotons value

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#467]
For each agent there should be amount of infotons which failed to be materialized
As following:
Running Agent A
Materialized X, Failed Y

**Comment by nicklester** [comment]
It looks as if the IngesterStats is only used by the data tools and will need to wire this in to the agent in order to show stats on the dashboard.

**Comment by nicklester** [comment]
![screen shot 2018-02-07 at 14 14 20](https://user-images.githubusercontent.com/1490089/35920970-482177c2-0c11-11e8-9451-d2eafcf9a835.png)

Implemented as shows in image

**Comment by nicklester** [comment]
Pull request for this feature created - #488
