### ISSUE TITLE
Remove batch,tlog from all the places in code

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#470]
checklist:
- [ ] All config files (check with DevOps) should remove the tlogDataDirs
  - [ ] This HD is freed or used for something else?
- [ ] In HealthActor change batchStatus to bgStatus

**Comment by hochgi** [comment]
Dup issue #426

**Comment by AnnaGrebnev** [comment]
was verified as part of the manual installation, will be fixed by DevOps in CM and verified by @GuyGuterman
