### ISSUE TITLE
Error 500 on searching a prefix

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#474]
On an environment with latest build (git commit hash 9ddf3326913216afd9bdb0d45764624877a8539e)
This request fails with error 500 http://cmwell-host/meta/ns?op=search&qp=prefix::rel&format=json
{"success":false,"error":"No field types bookkeeping was found for NnFieldKey(prefix)"}

This same request works on other environments. Data with this prefix rel is created as part of automated sanity tests - so this search should come back with results (1 result to be precise).

**Comment by hochgi** [comment]
After Quetzal, this won't happen in newly installed envs. Existing envs should be added mangling infotons for /meta/nn/prefix & /meta/nn/url if not existed (since won't be written unless new ns is added).

This is a sort of a data issue that needs to be patched once on existing envs.

**Comment by Ivan-Shestakov** [comment]
Validated on environment with git commit hash ea325a6c1ef1ca927dfbdf27706d58894baaa447
Searching using both prefix and url works as expected. 

Moving to Done.
