### ISSUE TITLE
Implement prefixes/ns identifiers new cache mechanism

### ISSUE THREAD

**Issue by hochgi** [thomsonreuters/CM-Well#476]
- should be time-based reactive (only updates from given point in time. no full reloads by default)
- should expose API to invalidate a key (manual purge of bad ns) - backed by #495 
- maybe: a limited (in size) blacklist with counters of calls tot 404 prefixes. try reloading specific prefixes once in a while

**Comment by Ivan-Shestakov** [comment]
List of stuff to test (WIP):

1. Add infoton which creates new prefix. 
    1. ntriples and json (most common) - observe new prefix created automatically (roughly abbreviate full url - `http://abc.def.hig/blabla` would become `adhb`
    1. n3 - contains both full namespace as well as desired prefix.
1. Retrieve infoton using prefix (`?op=search&recursive&qp=collaboratesWith.rel:`)
1. Retrieve infoton using identifier (`?op=search&recursive&qp=collaboratesWith.$r52U-w:`)
1. Retrieve infoton using full predicate value (`?op=search&recursive&qp=$http://purl.org/vocab/relationship/collaboratesWith$:`)
1. Add second prefix to existing url ( :question: using mark-replace flag?) and retrieve using both new and old prefix.
1. Modify existing prefix `curl -XPOST 'cm-well-host/_in?format=ntriples' -d '<> <cmwell://meta/ns#rel><http://purl.org/vocab/relationship/> .'`
1. The prefixes are cached in WS. Stop ES and try to access infoton. 
>>> Explanation: Before the fix, it would fail, because in Cassandra infotons are stored with their field identifiers (i.e. r52U-w) and we want to return them with their url/prefix values.

 :warning: Consider working in pe first (more control + easy cleanup) , only then move to multi-node environment.

**Comment by hochgi** [comment]
1. that's not how inference work. see:
https://github.com/thomsonreuters/CM-Well/blob/master/server/cmwell-ws/app/ld/util/LDFormatParser.scala#L881-L919
to test it, run:
`sbt ws/console` and execute: 
```
scala> cmwell.web.ld.util.LDFormatParser.inferShortNameFromUrl("http://abc.def.hig/blabla")
res0: String = blabl
```
BTW, the URL is missing a separator at the end...
also, it doesn't really matter...
2-4. are covered in unit test and integration tests
5. only a single prefix is allowed per namespace (currently. see #477 for future possibilities)
6. also covered in tests

**Comment by Ivan-Shestakov** [comment]
The new namespaces cache was tested manually, and automated tests validated no regression in existing functionality.

Moving to Done.
