### ISSUE TITLE
 Graph replace issue in CM-Well

### ISSUE THREAD

**Issue by PJLeyden** [thomsonreuters/CM-Well#479]
Graph replace command appears not to work correctly in CM-Well in that an insert happens but without the subsequent delete.  This affects reload and data integrity across the knowledge graph.

Looking at data it appears to be sent correctly as an insert and then an overwrite.
CM-Well seems to have ignored the replaceGraph used for the Overwrite sent.

Will provide further details and examples separately.

**Comment by sarahbatson** [comment]
See here for examples (pls also see email that is attached to that ticket for further examples): http://ent.jira.int.thomsonreuters.com/browse/LD-1927

**Comment by PJLeyden** [comment]
Closing issue.

**Comment by FlipGFlopTR** [comment]
@PJLeyden  - why has this been closed?  Does this mean the issue has been resolved?

**Comment by PJLeyden** [comment]
Replaced with internal JIRA issue.

**Comment by TRnonodename** [comment]
Hmmm - I'm not sure that replacing with an internal JIRA issue is the open we want CM-Well to be @PJLeyden. Anyone have issues with tracking it here rather than JIRA?

**Comment by hochgi** [comment]
`replaceGraph` API is just "syntactic sugar". you can achieve same results by searching `system.quad:<GRAPH URI>` and for every subject in result emit `<SUBJECT> <cmwell://meta/sys#markReplace> <*> <GRAPH URI> .`

Since CM-Well is "eventual consistent", one cannot expect this API to work on recently added entries.

**Comment by YoniMataraso** [comment]
@TRnonodename - the main reason for closing this issue, is that we don't have the generic issue here. We weren't able to reproduce the issue so far. The data we have is internal. so Having it logged internal until further investigation is done sounds reasonable for me.

**Comment by TRnonodename** [comment]
OK.. if the issue is likely in an internal process working with CM-Well that's fine to be internal. Someone has to be the open cop :-)

**Comment by FlipGFlopTR** [comment]
@hochgi - looking at the details; the issue seem to persist indefinitely so I'm not sure that this is a transient issue.  However, as there is an internal ticket for this, I'm OK that investigations are continuing.
