### ISSUE TITLE
Span Kafka LogDirs over more than one node

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#483]
Also - reduce retention from one week to one day (24hrs)

**Comment by Ivan-Shestakov** [comment]
Validated on 2 lab environments: one fresh install, and another upgrade. 
The manual change required was to update environment configuration to take a `List("/kafka//folder")` instead of `"/kafka/folder"` 
Sanity passed (except for known failures (424 errors)).
