### ISSUE TITLE
Qstream API: incorrect number of infotons appear in the response (127 vs expected 3000)

### ISSUE THREAD

**Issue by GuyGuterman** [thomsonreuters/CM-Well#485]
Tested by using `curl -v --raw` and output to file, then stream for few seconds and counted.
The results can be seen below:

Search param | Expected result | Actual result
-- | -- | --
Tested with used curl -v --raw and default length-hint (not registered as parameter)  | about count 3000 | Result was ~127
Tested with used curl -v --raw and default length-hint equal to 50 | about count 50  | Result was ~37
Tested with used curl -v --raw and default length-hint equal to 1500 | about count 1500 | Result was ~127
Tested with used curl -v --raw and default length-hint equal to 3000 | about count 3000 | Result was ~127

Conclusion: 
`**Default length-hint of 3000 not working and any change manually does not bring an equal result to the request that has been entered**`

**Comment by hochgi** [comment]
@GuyGuterman 
> incorrect number of infotons ...

How can you tell  with `curl`?
the chunk size determines that length of result set CM-Well get's internally from ES.
Not how it is outputted by play server...

HTTP chunk size is irrelevant. we should check ES responses to WS instead.

**Comment by GuyGuterman** [comment]
@hochgi 
With curl and -o, --output FILE wrote to an output file, using the file I counted the quantity.
How ES responses to WS (if) records this action at the log?

**Comment by hochgi** [comment]
quantity of entire results? how many infotons does your query should return? is it 3K or more? maybe there's only 127 results... can you threw a quick example?
sample data to ingest + query that fails over that data.

**Comment by GuyGuterman** [comment]
After discussing with @hochgi -The error was found, the reason for the resulting ~127 is reported to client-side and not directly from ES to WS.
Will be closed.
