### ISSUE TITLE
Mangling cache should have a size cap

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#491]
And LRU semantics.

Phase 2 can be 2 LRU populations (OS Pages Cache style)

**Comment by AnnaGrebnev** [comment]
@Ivan-Shestakov please check

**Comment by Ivan-Shestakov** [comment]
The size cap is soft, so new entries will always get added to cache. 
At the moment no automatic invalidation happens, so /_ns-cache?invalidate or ws restart is the way to cleanup (needed only if a user abuses the system by mistake flooding the namespaces) . 

Manual test for /_ns-cache json retrieval and invalidation.

Action | Expected | Actual
---- | ---- | ---- 
curl -s 'cm-well-node:9000/_ns-cache' | Check size of cache by piping to jq ".mainCache|length" |  89 | 
curl -s "cm-well-node:9000/_ns-cache?invalidate-all" -H "X-CM-WELL-TOKEN:xxxx-xxxx"``` | {"success":true}
`curl -s 'cm-well-node:9000/_ns-cache' | Validate that the cache was cleaned | 0 as expected.

The effect of namespace caching was tested on lab environments - using frontend regression and customer use cases.
Moving to Done.
