### ISSUE TITLE
Meta Infotons writes should also add mang field when needed

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#494]

**Comment by Ivan-Shestakov** [comment]
Validated that on creation of new namespace prefixes, fields and their mangling type were processed successfully. 
Those are the steps:
1. Run Automated Frontend sanity ( to populate testing data) 
2. 'curl -v 'cm-well-host/meta/ns?op=stream&with-data&recursive' -o temp`
3. 'cat temp | sort -k1,1 -k2,2n | grep 'prefix> "ns' to find the prefix hash.
4. `cat temp | sort -k1,1 -k2,2n | grep CGfbrA` (found in step 3)  and verify that all fields have appropriate mangling: for example 
```<http://cm-well-host/meta/ns/CGfbrA/Boolean1> <http://cm-well-host/meta/nn#mang> "b" .```

Moving to Done
