### ISSUE TITLE
STP Dashboard - Materialized statistics should count ingested infotons only

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#500]
Statistic of materialized infotons gives the number of infotons which were materialized only without any count of successfully ingested infotons
The number of materialized infotons is less important because there is a need to know how much were actually ingested
We can do the following -
Change Materialized  to Ingested or
Add Ingested and failed count to the STP Dashoard

**Comment by YoniMataraso** [comment]
Let's get rid of the materialized stats and only keep ingested and failed values.

**Comment by nicklester** [comment]
Implemented as attached
 
![screen shot 2018-02-14 at 13 52 27](https://user-images.githubusercontent.com/1490089/36207974-7aca72fe-118f-11e8-8c82-7da33df29cfa.png)
