### ISSUE TITLE
Better error messages from _sp

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#503]
We should refactor `_sp` so it will only return errors in JSON (i.e. `{"success":false,"message":"..."}`).
Changing the response code once we already started dripping newlines is not possible, but having the error message wrapped in a JSON might help _sp clients to distinguish more easily between data and errors.

**Comment by nicklester** [comment]
This problem seems to manifest in STP. A case in point is the linked #434. The literal string "Busy, try again later" is passed downstream to the Ingester as a 200 is returned and not a 503 in some circumstances

**Comment by YoniMataraso** [comment]
Let's try to see if we can add an addition HTTP response header instead of the json response body.

**Comment by GuyGuterman** [comment]
Tested by:

curl -v cmwell/_sp --data-binary 'PATHS
1path
2path
3path

SPARQL
CONSTRUCT { ?s ?p ?o . } WHERE { ?s ?p ?o }'

Results will be changed by output: HTTP/1.1 200 OK and if will be an issue with PATH will be responded X-CM-WELL-SG-RS: with error codes, CW get in response. 

Search | Expected result | Actual result
-- | -- | --
3 PATHS exist | NO X-CM-WELL-SG-RS | X
2 PATHS exist | NO X-CM-WELL-SG-RS | X
1 PATHS exist | NO X-CM-WELL-SG-RS | X
1 PATH does not exist in list | ONE X-CM-WELL-SG-RS: 404 | X
2 PATH does not exist in list | TWO X-CM-WELL-SG-RS: 404, 404 | X

Conclusion:
Tested and PASSED
Move this from Testing to Done

**Comment by AnnaGrebnev** [comment]
@GuyGuterman it is not enough to test it with the simple SPARQL, we should cover it with the real list of queries.
