### ISSUE TITLE
Proc pages parsing fails

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#505]
try to get api: /proc/health-detailed?format=json
Following error appears:
ERROR c.c.q.t.c.a.Utils - Incorrect status code is returned: 503. ErrorMsg: {"success":false,"error":"Internal old API (hashToUrlAndPrefix) used on id [7*], which was not yet in cache. subsequent requests should succeed eventually. Call should be migrated to new API"}

**Comment by hochgi** [comment]
fixed in fa5ee60349961e2daabd33312e88d235558a4a0d
