### ISSUE TITLE
NameSpace issue - Deal prefix doesn't work till ingesting infoton manually

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#508]
Installed UK
There is following namespace on start of the system:
meta/ns/OfU7SQ
<http://cmwellhost/meta/ns/OfU7SQ> <http://cmwellhost/meta/nn#url> "http://feed.thomsonreuters.com/ontology/Deal" .
<http://cmwellhost/meta/ns/OfU7SQ> <http://cmwellhost/meta/nn#prefix> "Deal" .

Started dealsjv sparql which suppose to write infotons to http://feed.thomsonreuters.com/
All ingest fails with status=503 Service Unavailable entity=HttpEntity.Strict(application/json,{"success":false,"error":"Internal old API (urlToHash) used on id [http://feed.thomsonreuters.com/ontology/Deal/], which was not yet in cache. subsequent requests should succeed eventually. Call should be migrated to new API

After ingesting some infoton to http://feed.thomsonreuters.com/, problem solved but one more Deal namespace was created:
dure2w
<http://cmwellhost/meta/ns/dure2w> <http://cmwellhost/meta/nn#url> "http://feed.thomsonreuters.com/ontology/Deal/" .
<http://cmwellhost/meta/ns/dure2w> <http://cmwellhost/meta/nn#prefix> "Deal" .

The between two namespaces is a  "/" in the end 

ID | prefix | URL
-- | -- | --
dure2w | Deal | http://feed.thomsonreuters.com/ontology/Deal/
OfU7SQ | Deal | http://feed.thomsonreuters.com/ontology/Deal

**Comment by hochgi** [comment]
The fact the 2 namespaces were created is not a CM-Well issue... that's user error.
The other issue described here is:
- another user error -> you can't search something that does not exist yet
- code was changed, and this specific error won't occur
