### ISSUE TITLE
STP - ingest of materilized infotons is not working on environments with useAuthorization=true

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#514]
Because of the fact that STP using same token as DC which is defined to work only with _ow and not with _in, ingest of materilized infotons will not work on environments with useAuthorization=true
For current version, there is a need to enable _in for this token 
For next version there is a need to create a new user for STP only

**Comment by e-orz** [comment]
Talked to Yaakov. The current token also allows writing. The issue in the lab should be investigated but it's not related to the token.

**Comment by yanpom** [comment]
Ingest doesnt work because it use no token

**Comment by nicklester** [comment]
Will create a new STP user with correct permissions and get the configurable token in the headers for _in

**Comment by nicklester** [comment]
- Create new STP user in install scripts
- Take token from env var if not supplied in reference.conf
- Pass token to ingester _in API call
