### ISSUE TITLE
STP agent- Incorrect horizon notification

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#548]
Run dealsjv agent
One of the sensors - deals suppose to get 157000 results
It downloads 22270 infotons and set as horizon (meaning getting 204 from server -PLEASE ADD IT TO LOG)
then it brings no more infotons for 10 minutes and then brings another 10K infotons...in this way it gets more infotons each several minutes but the state is always horizon

**Comment by nicklester** [comment]
We decided to set horizon when a 204 is received by the BufferFillerActor. However the buffer can run up to one million paths, so it can show horizon long before infotons have materialized and ingested. We need to think about using a trigger of an empty / almost empty buffer - @yanpom / @YoniMataraso  ?

**Comment by yanpom** [comment]
I suggest to receive number of infotons per qp of the sensor and store it. (The search should be from the latest token timestamp (or 1970 if such doesnt exist) Only when reaching this number the sensor state should change to horizon
