### ISSUE TITLE
STP - dealsmna agent incorrect functionality

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#553]
According to dealsmna agent configuration, it suppose to pull from ppe, 1093040 infotons,
In fact it pulls 1093003 infotons (37 infotons are missing) 
But the materialization and ingest done only for 1040878 infotons (more then 50K pulled infotons are not materialized)
Regarding the ingested infotons, in fact only 1040868 infotons where ingested to cmwell (10 infotons are missing if trusting the statistics)
All materialized infotons ingest succeed, nothing new (unknown) in logs

**Comment by nicklester** [comment]
PR #599 raised to re-try certain errors to prevent this data loss

**Comment by nicklester** [comment]
Working with LinkedData team to confirm if latest materialisation worked as expected

**Comment by nicklester** [comment]
We can't see any concrete issues with the materialisation which suggest STP has any specific issues. Missing infotons seem to be due to data issues. 

Can we close this and open cases if we can still identify a specific issue?
