### ISSUE TITLE
STP Dashboard - Token time appears despite of the fact that token doesnt exist

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#560]
Started dealsjv agent 
Tokens ingest failed - see issue https://github.com/thomsonreuters/CM-Well/issues/559
But one of the tokens time changed from blank to actual time point despite of the fact that such token doesn't exist

**Comment by nicklester** [comment]
I don't think this is a bug per-se. The STP is still up to that token position, it just failed to persist the token due to issue #559. The token saving error _is_ logged, so I don't think we should handle this any other way? Thoughts @yanpom

**Comment by yanpom** [comment]
As I understand, the time which suppose to appear in token time column is the actual timestamp of created token. So I don't understand exactly how does it appear if token was not created.

**Comment by nicklester** [comment]
The last token used for the consume API is stored in the state of the BufferFillerActor and represented on the dashboard. It just doesn't persist the token as an infoton because of #559 which has now been fixed with a PR raised...

**Comment by yanpom** [comment]
Understood. But this doesnt explain why other sensors were empty...they started working together but it took a while for them to get some value
