### ISSUE TITLE
STP - SPARQL response body validator issue

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#578]
The code to validate response body does not cover all scenarios. i.e.
 !(body containsSlice "Could not process request")
looks for a specific string to invalidate the response. It is possible empty responses or other errors can slip through this...

**Comment by YoniMataraso** [comment]
@bryaakov and myself thinks its related to #503

**Comment by nicklester** [comment]
Agree - looked further and tested. Pretty certain its the same issue.

**Comment by nicklester** [comment]
PR #599 raised to address this
