### ISSUE TITLE
Links don't work in the new UI

### ISSUE THREAD

**Issue by TRnonodename** [thomsonreuters/CM-Well#59]
If an object is a link/relationship, in the old UI you could click on it and go to the relevant Infoton. In the new UI the browser tries to load as a page and CM-Well navigation is lost. 

Steps to recreate:

Load TRCS from permid.org
Navigate to Adhesives
http://locahost:9000/permid.org/1-4294951936
Try and navigate to the broader topic

Interestingly this doesn't incur on internal servers, so I suspect the old_ui query string param might be to blame?

**Comment by YoniMataraso** [comment]
I think this was fixed, if you will try it agin using the latest version it seems to be working
