### ISSUE TITLE
STP Engine - better logging is needed in case that _sp matertilize gets partial results

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#605]
The error which received is: 
received 200 OK but response body is not valid, will retry again in 30 seconds host=<hostName> data=<infoton>
There is a need in add to this message 
"Sparql received partial results,  X-CM-WELL-SG-RS = <responseCode>

**Comment by nicklester** [comment]
Added response validator logging in PR #607

**Comment by yanpom** [comment]
Verified and closed
