### ISSUE TITLE
STP - materialization is broken in latest version

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#625]
EGL1: All _sp requests returns with X-CM-WELL-SG-RS : 422 when running STP Agent with local source (EGL1)
Works when configuring to work with PPE
Works when sending separate _sp to EGL1 (with fiddler)

**Comment by nicklester** [comment]
Turned out to be an issue with missing namespace prefixes in egl1

**Comment by yanpom** [comment]
Correct
