### ISSUE TITLE
UI - View content in different format does not display UTF-8 characters incorrectly  

### ISSUE THREAD

**Issue by YoniMataraso** [thomsonreuters/CM-Well#626]
When trying to view infoton in another format(json, Ntriples, etc..) using the view dropbox for infotons which contains UTF-8 characters those characters are displayed incorrectly.

**Comment by YoniMataraso** [comment]
After reviewing the code with @bryaakov we have identified a missing charset=utf-8 is missing and therefore is not displayed correctly on a browser.

**Comment by GuyGuterman** [comment]
Validated by ingesting infotons with text UTF-8 (few different languages). View in various formats (json, Ntriples, etc..). Repeated few times.
Moving to Done
