### ISSUE TITLE
New CM-Well installation fails on unsupported java version

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#638]
When installing new environment on AWS based cluster, the installation process gets stuck on this error:
kafka/admin/TopicCommand : Unsupported major.minor version 52.0

All the preparation steps are done without errors (including prepare machines).
As temporary workaround I had to export JAVA_HOME environment variable in user 'u' .bashrc file, but it's not a good way to go with.

**Comment by GuyGuterman** [comment]
Test and Verified PASSED 
On AWS cluster, tested few times with different numbers of nodes.
Moving to Done
