### ISSUE TITLE
STP - consume infotons statistics and token info get cleared during STP work

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#644]
During 2 weeks of running oafull and person sparqls on PROD  everything worked good as expected till today, during the morning there were many messages of queue capacity reached 1000 and EsRejectedExecution Exceptions.
As a result of that manager was restarted several times during several minutes... Then the work proceed
What also happened as a result of that, is that some of sensors consume statistics were cleared and started from scratch.

**Comment by yanpom** [comment]
This is a critical bug which cause the sensor work restart from scratch
There is a need in some validation test, prior ingesting new infoton - if the indexTime of new token is older then the current one we should not ingest new infoton (same with consuming stats). If someone wants to start from scratch, he will delete the token.

**Comment by nicklester** [comment]
@yanpom is it just stats that restart, or is the token position restarted and the job starts from scratch?

**Comment by yanpom** [comment]
token position restarted,
Stats cleared to 0
everything starting from scratch

**Comment by nicklester** [comment]
StpUtil reads previous infotons, but I don't think there is enough error handling if the call times out or receives some other non 404 error code. This will lead the agent into assuming there is no persisted token infoton and will start from scratch.

Should we retry x amount of times and pause the agent if we cannot determine if there is an infoton or not - i.e. only continue if we get 404 or 200?

**Comment by nicklester** [comment]
Fixed in PR #686
