### ISSUE TITLE
spQueryParamsBuilder parameter of createSparqlSourceFromPath needs to be configurable

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#648]
Something that is confusing me is the purpose of spQueryParamsBuilder parameter (function) of the SparqlProcessor.createSparqlSourceFromPaths function. It seems to split by the last hyphen and retain the latter portion. 

The infoton paths I am working with look a little like - /data.thomsonreuters.com/26-tag_reuters_com_2018-02-26_newsml_NRA6crkw7_1 so the function returns 26_newsml_NRA6crkw7_1, and this is passed as the sp.pid parameter to the _sp API. Consequently we can't find the infoton and the _sp call fails.

Agent configuration needs to specify how this extraction function works. Can we consider a regex extractor?

@yanpom - assigned this to you for your thoughts...

**Comment by yanpom** [comment]
Verified and closed
