### ISSUE TITLE
STP - Token infotons has too many history instances - there is a need in limitation

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#649]
There is no limitation for history instances for an infoton
This causes the token infotons to have 1400 history instances in 2 weeks.
There is no need in such huge number of instances - please limit it to X days or Y instances per infoton

**Comment by YoniMataraso** [comment]
This will be resolved as part of the work on the statistics persistence over zstore #644

**Comment by nicklester** [comment]
Fixed in PR #692

**Comment by yanpom** [comment]
Moved to zstore. not relevant now
Closed
