### ISSUE TITLE
Fix BgActors recovery across cluster

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#654]

**Comment by Ivan-Shestakov** [comment]
**Details**
The following tests were done:

1.  Stop bg process on a node. Observe the bgActor jumping to another node. Do ingest of known set of data, to make sure all is in working order. PASS.
2.  Stop bg process on a node which runs 2-3 bgActors. Observe the actors jump to other nodes (according to N, N+1, N+2 formula - node 0 can run actors 0,1,2) . Do ingest afterwards. PASS.
3.  Start an ongoing ingest and repeat test 1. 1.1M infotons, which are uploaded for 16 minutes. Verify same amount ingested as without interruptions. Time taken - a bit faster (31seconds less). PASS.
4.  Start an ongoing ingest and repeat test 2. 1.1M infotons, which are uploaded for 16 minutes. Verify same amount ingested as without interruptions.  PASS.
5.  Start an ongoing ingest and this time REBOOT the node (our past experience shows this is more common, than specific process crash). The ingest time was 5 minutes more (20 minutes 44 seconds). Total ingested infotons 5693 less than when ingest wasn't interrupted. FAIL

    A correct comparison would be to run same tests against Swan environment to see behavior before change to bgActor rebalancing.
    Ingest data loss occurred only when restarting the whole node - so maybe another component is to blame for it (ws? or even data tools?).

> To ingest data, the path of the infotons was modified between the runs, to make sure no null updates are complicating the counts.
