### ISSUE TITLE
STP agent - Only 10 agents are running in parallel, others are stopped

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#693]
Started 15 agents in PPE, one by one, during the start, some other agents stopped,
After started all agents and there are 15 in meta/sys/agents/sparql which suppose to run, in dashboard there are only 10 agents,
Log sent separately

**Comment by nicklester** [comment]
https://github.com/thomsonreuters/CM-Well/pull/697

Search to retrieve config infotons only returning 10. PR above raised
