### ISSUE TITLE
STP - Inconsistency in saving sensors tokens to zstore

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#703]
Ran oafull on UK
6 sensors out of 8 were created immediately and were frequently updated
oafulloa-identifiers created in zstore after 3 hours when it was already 350K infotons consumed
oafulloa-hierarchy with more then 400K consumed infotons still not created after 3 hours

**Comment by nicklester** [comment]
All sensors are now up to date. The logic here is no different to what was before with infoton storage. Possibly not enough infotons had been materialised from the stream to mean that another chunk would be requested from the buffer and therefore write a token.

Is this still an issue to remain open - @yanpom @AnnaGrebnev

**Comment by nicklester** [comment]
On investigation there is no actual issue with token saving. The sesnors in question could not resolve sparqlToRoot paths from old data. Therefore I don't think there is an open issue
