### ISSUE TITLE
Modify Cassandra replication strategy (on new install)

### ISSUE THREAD

**Issue by YoniMataraso** [thomsonreuters/CM-Well#718]
Our current replication strategy is set to simpleStrategy which is not appropriate for cluster based deployment. Update replication strategy to "NetworkTopologyStrategy".

@yanpom Please check both options: Install and upgrade

**Comment by GuyGuterman** [comment]
Test and Verified
Compare with Install and Upgrade working environments, as expected in the environment with Install replication strategy was change to new. in environments with Upgrade no change (same as previous).
Close & Moving to Done
