### ISSUE TITLE
STP - Enhancement - Decrypt token inside the zstore

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#719]
Now than all tokens are secured and written to zstore, I think we can decrypt them and present in normal view, this will save time in monitoring the agent progress

**Comment by nicklester** [comment]
@yanpom - not sure I follow. The token is decrypted and shown in the dashboard already. Are we talking about something else?

**Comment by yanpom** [comment]
its encrypted
I want to decrypt it

**Comment by nicklester** [comment]
Understood. Will be adding a new position field in the stores zstore json to display this

**Comment by yanpom** [comment]
Verified and closed
