### ISSUE TITLE
STP - Reduce BufferFillerActor buffer size

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#730]
The size of the buffer (300,000) is too large and leads to the STP downloading too many TSVs when the process starts. It also leads to a misleading remained infoton count on the dashboard.

Need to consider reducing this to a more sensible size. 

This large buffer is probably a hangover of having used bulk consume.

Need to ensure the new buffer size is configurable

**Comment by yanpom** [comment]
Verified and closed
