### ISSUE TITLE
dc crawler reports correct data chunking as error

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#750]
When CM-Well stores binary data (for file infotons) in Cassandra, it splits them to several chunks.
Data Consistency Crawler reports existence of those chunks as duplicate system fields.
Example from crawler.log file:
```
Crawler [persist_topic, partition: 1]: Inconsistency found: Duplicated system fields! field [da│
ta] has too many values [0,1] for command in location [persist_topic, partition: 1, offset: 83501688]. Original command: WriteCommand(FileInfoton(/meta/docs/_Images/ui-message-banner.png,egl1,None,2018-06-13T11│
:47:18.113Z,None,Some(FileContent(Some([B@7c957f0c),image/png,127193,None)),),None,None) ```

**Comment by e-orz** [comment]
It's a regression introduced in commit
b511b373b61bbe0077b736c89e737d67403713f4
when the filter moved to cas instead of inside the crawler.
