### ISSUE TITLE
STP - Use cached connection pool and make akka config for STP configurable

### ISSUE THREAD

**Issue by nicklester** [thomsonreuters/CM-Well#751]
In order to address the excessive load created by multiple agents all using their own connection pools we will move to a single pool

**Comment by yanpom** [comment]
Please add additional information here
Where the change applies, what is the change etc..Please add some info

**Comment by nicklester** [comment]
Data tools configuration is now separated - see data-tools section of dc application.conf. Cached connection pool was tested and did not work as expected. So I think we can close?
