### ISSUE TITLE
Crawler management: API to turn off/on

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#760]
Similar to Backpressure feature and the `/_backpressue` API.
- Default will be: Running
- Invoking `/_crawler` without any query parameters will return current state
- Invoking `/_crawler?op=[stop|start]` will stop or start the Crawler, respectively
- Will require an Admin token
- `op=detect-only` will also be supported

**Comment by e-orz** [comment]
Please notice: disabling crawler will cause "detection loss" due to retention logic of Kafka.

**Comment by Ivan-Shestakov** [comment]
@bryaakov was this implemented? Or parked aside for some distant future?

**Comment by bryaakov** [comment]
Not implemented. @YoniMataraso, do we even want this?
