### ISSUE TITLE
Duplicates!

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#767]
We found 21M duplicates on one of our cluster.

Use case: replace-mode

Distribution:
```
4,4,4,5,5,7,12,15,19,22,23,24,48,73,102,115,137,164,168,179,198,277,296,372,548,564,636,744,2814,3477,8654
```

And about 20M more of 2 and 3.

We suspect `setVersion(1)` in both x-fix and bg, we will have to see if it helps.

* This code was not modified lately, so there may be more causes for that.

**Comment by YoniMataraso** [comment]
We are trying to reproduce the same scenario on a lab environment
