### ISSUE TITLE
dcc continuosly crashes if system.uuid field isn't found in Elastic document

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#770]
To reproduce on pe:
1) enable inline scripting in es.yml: add `script.inline: true` to app/cm-well/conf/es/es.yml and restart elastic search.
2) locate an infoton in elastic, and delete the "uuid" field:
curl localhost:9201/cm_well_p0_0/infoclone/c9937ea222b08019b2162a83f54201ce/_update -d ' {"script" : "ctx._source.system.remove(\"uuid\")"}'
3) reset crawler offsets and restart bg.
Observe continuos restarts of crawler by bgActor.

**Comment by YoniMataraso** [comment]
After a discussion in the grooming meeting we have decided that this case is too artificial and will not be handled. In other cases we will strive to prevent DCC and other components from getting stuck, rather report the issue to the red log and move forward.
