### ISSUE TITLE
Asterisk Java AMI dialing out 

### ISSUE THREAD

**Issue by lexerpv** [thomsonreuters/CM-Well#794]
Hi
I'm trying to make a asterisk-java program (HelloManager) that dial from a sip extension 100 to sip extension 103 (I got the code from https://asterisk-java.org/tutorial/  HelloManager), this the asterisk-java code:

`import java.io.IOException;

import org.asteriskjava.manager.AuthenticationFailedException;
import org.asteriskjava.manager.ManagerConnection;
import org.asteriskjava.manager.ManagerConnectionFactory;
import org.asteriskjava.manager.TimeoutException;
import org.asteriskjava.manager.action.OriginateAction;
import org.asteriskjava.manager.response.ManagerResponse;

public class HelloManager
{
    private ManagerConnection managerConnection;

    public HelloManager() throws IOException
    {
        ManagerConnectionFactory factory = new ManagerConnectionFactory(
                "localhost", "manager", "pa55w0rd");

        this.managerConnection = factory.createManagerConnection();
    }

    public void run() throws IOException, AuthenticationFailedException,
            TimeoutException
    {
        OriginateAction originateAction;
        ManagerResponse originateResponse;

        originateAction = new OriginateAction();
        originateAction.setChannel("SIP/100");
        originateAction.setContext("from-internal");
        originateAction.setExten("103");
        originateAction.setPriority(new Integer(1));
        originateAction.setTimeout(new Integer(30000));

        // connect to Asterisk and log in
        managerConnection.login();

        // send the originate action and wait for a maximum of 30 seconds for Asterisk
        // to send a reply
        originateResponse = managerConnection.sendAction(originateAction, 30000);

        // print out whether the originate succeeded or not
        System.out.println(originateResponse.getResponse());

        // and finally log off and disconnect
        managerConnection.logoff();
    }

    public static void main(String[] args) throws Exception
    {
        HelloManager helloManager;

        helloManager = new HelloManager();
        helloManager.run();
    }
}`

I'm using the library: **asterisk-java-1.0.0-m2.jar**

I put java program and library in the java directory on asterisk.

When I compile the using :**`javac -cp asterisk-java-1.0.0-m2.jar HelloManager.java`**

I recieve the following error:

Note: HelloManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I compile using: **javac -cp asterisk-java-1.0.0-m2.jar HelloManager.java -Xlint:deprecation**

I receive;

HelloManager.java:33: warning: [deprecation] setTimeout(Integer) in OriginateAction has been deprecated
        originateAction.setTimeout(new Integer(30000));

If remove the line codeon my program:   originateAction.setTimeout(new Integer(30000));

The program compiles, But when I try to run program using:  **java  HelloManager**

I recieve the error:

**```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/asteriskjava/manager/action/ManagerAction
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.asteriskjava.manager.action.ManagerAction
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```**


I dont know what I'm doing wrong, Please, any ideas?

**Comment by YoniMataraso** [comment]
@lexerpv I think you opened the issue in the wrong project?

**Comment by bryaakov** [comment]
incorrect repo...
