### ISSUE TITLE
Post Upgrade Actions - Phase 1: Add properties file

### ISSUE THREAD

**Issue by MoriaYechiel** [thomsonreuters/CM-Well#804]
Create properties file to hold data describing the current build.
File will hold: 
1. git_commit_version
2. cm-well_release
3. cm-well_version

This issue is first step towards #776

**Comment by GuyGuterman** [comment]
Test and Verified
After the building package, the creation process creates a new file with the name: `cmwell.properties` 
Close & Moving to Done
