### ISSUE TITLE
dcc crawler reports false positive duplicates

### ISSUE THREAD

**Issue by Ivan-Shestakov** [thomsonreuters/CM-Well#808]
When analyzing the crawler logs on environment with 5a2151ea1172d82cda2bc272c56ff2ca97654bfa it reports inconsistency of unexpected property of [true] of specific command.
Reviewing the kafka messages + application logs, we understand that at the moment when crawler processed the record, new version existed in Cassandra, but not in Elastic, thus it was an actual inconsistency. Rerunning crawler on same offsets again, we don't get those errors, as 'eventual consistency' mechanism worked, and the version was set to current:false appropriately.

**Comment by e-orz** [comment]
It's actually a check that is not needed. Bg always writes the current version with current:true.
This check is removed (only prints info in the logs).
Fixed in PR #810

**Comment by Ivan-Shestakov** [comment]
Verified on Viper version with git hash ae9c849ab4afa9f4176cc45fc49ea16b7f316b10 
Doesn't reproduce in the same scenario (massive ingest in 40x4 connections).
Moving to Done.
