### ISSUE TITLE
Bg streams (imp, indexer, crawler) crash when there is some pressure on CAS

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#811]
offsetService.write is synchronous and has `Await.result` of 10 seconds. If for some reason CAS has a delay of more than 10 seconds the whole stream crashes.

**Comment by GuyGuterman** [comment]
Test and Verified
Check before and after fices version by load millions of infotons and tested processes + logs files.
Close & Moving to Done
