### ISSUE TITLE
In case the offset persisted is not reasonable upon start Bg hangs

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#823]

**Comment by GuyGuterman** [comment]
Test and Verified PASSED

Those are the steps:
1. Stopped all BGs at the all cluster 
2. 'ps aux | grep bg.Runner ' 
3. Checked what is the upper and lower offset in kafta with: `./kafka-simple-consumer-shell.sh`
4. One partition was set with upper offset `--offset -1`
5. One partition was set with lower offset `--offset -2`
6. Check whether the parameters have been updated as required at imp_ on each partition.
7. Start of all BGs `HAL=9000 /opt/cm-well/app/bg/start.sh`
8. Check again each partiotion what is the offset was set (need to be the same, initial number of KAFKA (Step three)
9. Checked at all BGs log (application.log) for existing log for this cahnges: *"It probably means data loss"*

This issue will be closed
