### ISSUE TITLE
Search by post not available for root path

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#843]
reproduce:

```
curl "localhost:9000/example.org?op=search" -H Content-Type:application/x-www-form-urlencoded --data-binary 'recursive=true&qp=FN.vcard::Jane%20Smith&format=tsv'
/example.org/JaneSmith	2018-07-29T08:47:15.665Z	844a646f09b1e39b1be144e8d4f4fbbf	1532854035927
```

However, when `example.org` is missing, the response is 400 from Play.

@GuyGuterman please check and update the automation tests if it's required.

**Comment by GuyGuterman** [comment]
Test and Verified
Check `?op=search` by `GET` and by `POST` with different `qp`. Comparison of the results was made by equality between HTTP Methods.
Will be adding to Automation.
Close & Moving to Done
