### ISSUE TITLE
Compress kafka messages

### ISSUE THREAD

**Issue by MoriaYechiel** [thomsonreuters/CM-Well#855]
In order to save disk space, we will add compression support for messages to Kafka's queues.

**Comment by GuyGuterman** [comment]
Test and Verified
Check before and after an upgrade the new version by: `./kafka-run-class.sh kafka.tools.DumpLogSegments --files /opt/cm-well/data/kafka/persist_topic-x/000000000000000000000.log --print-data-log `.
New version working with `compression: LZ4`
Close & Moving to Done
