### ISSUE TITLE
Set Kafka retention to 1 Week

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#865]

**Comment by GuyGuterman** [comment]
Test and Verified
Compare with Install and Upgrade working environments. Check settings to Kafka by: `/opt/cm-well/conf/kafka/server.properties`
Tested environment over a week, each day tested Kafka queue for the first infoton at the queue by: `kafka-simple-consumer-shell.sh --broker-list localhost:9092 --max-messages 1 --offset -2 --partition 0 --print-offsets --topic persist_topic`
Close & Moving to Done
